# Notes

In [ ]:
import numpy as np                  # "numpy" is a library in Python that collects the operations of matrices.
from numpy.linalg import inv

In [ ]:
A = np.array([[1,2], [3,4], [5,6]]) # define matrix in Python
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B = np.array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
C = np.array([[3,-3], [4,-4]])
D = np.array([[5,-5], [6,-6]])

In [ ]:
C@D            # matrix multiplication

array([[-3,  3],
       [-4,  4]])

In [ ]:
from numpy.linalg import matrix_power
matrix_power(C, 4)

array([[-3,  3],
       [-4,  4]])

In [ ]:
C@C@C@C

array([[-3,  3],
       [-4,  4]])

In [ ]:
C*D            # element-wise multiplication

array([[15, 15],
       [24, 24]])

In [ ]:
C+D            # matrix addition

array([[  8,  -8],
       [ 10, -10]])

In [ ]:
C-D            # matrix subtraction

array([[-2,  2],
       [-2,  2]])

In [ ]:
E = np.array([[1,-3], [-5, 7]])
inv(E)         # matrix inverse

array([[-0.875, -0.375],
       [-0.625, -0.125]])

In [ ]:
E@inv(E)

array([[1., 0.],
       [0., 1.]])

In [ ]:
inv(E)@E

array([[1., 0.],
       [0., 1.]])

In [ ]:
E.T           # matrix transpose

array([[ 1, -5],
       [-3,  7]])

In [ ]:
F = np.arange(10)         # define a sequence of 10 numbers starts from 0 to 9
F

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
F[2]          # note that the index of matrix/array in Python starts from 0

2

In [ ]:
F[0]

0

# Exercise

1(a). Define a row matrix stores the sequence from 0 to 20.

In [ ]:
s = np.arange(21)

1(b). Find the sum of seventh power of each element in the row matrix in (a).

In [ ]:
abs(np.sum(s**7))

417680596

2. Let $M = \left[\begin{matrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \end{matrix}\right]$.

(a). Find $M^2$ and $M^3$.

In [ ]:
M = np.array([[0,1,0,0], [1,0,0,0], [0,0,0,1], [0,0,1,0]])

In [ ]:
print('M^2 = ')
print(M@M)
print('')
print('M^3 = ')
print(M@M@M)

M^2 = 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

M^3 = 
[[0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]


(b) Verify $M^{-1} = M$.

In [ ]:
inv(M)-M

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])