# Notes

For a square matrix $A$, the values $\lambda$ such that $A\lambda = \lambda v $ is called the eigenvalues of $A$. The corresponding vector $v$ satisfies the equation $A\lambda = \lambda v$ is called the eigenvector.

## ```How to Find Eigenvalue and Its Corresponding Eigenvector```

(a) Solve the equation $det(A-\lambda I) = 0$ for the eigenvalues $\lambda$.

(b) For the eigenvalues found in (a), solve the system $(A-\lambda I)v = 0$ for the eigenvector $v$.

In [ ]:
import numpy as np
from numpy.linalg import inv, eig

In [ ]:
E = np.array([[1,-3], [-5, 7]])
E

array([[ 1, -3],
       [-5,  7]])

In [ ]:
value, vector = eig(E)        # eigenvalue and eigenvector of matrix E

In [ ]:
value

array([-0.89897949,  8.89897949])

In [ ]:
vector                        # Python will normalized the eigenvectors. (i.e. The eigenvectors computed are unit vectors.)

array([[-0.84494897,  0.35505103],
       [-0.53484692, -0.93484692]])

In [ ]:
F = np.array([[2,0,0], [0,3,4], [0,4,9]])
F

array([[2, 0, 0],
       [0, 3, 4],
       [0, 4, 9]])

In [ ]:
value1, vector1 = eig(F)

In [ ]:
value1

array([11.,  1.,  2.])

In [ ]:
vector1

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.4472136 ,  0.89442719,  0.        ],
       [ 0.89442719, -0.4472136 ,  0.        ]])

# Exercise

1. Let $M = \left[\begin{matrix}
-13 & -8 & -4 \\
12 & 7 & 4 \\
24 & 16 & 7\end{matrix}\right]$. Find the eigenvalues and eigenvectors of M.

In [ ]:
M = np.array([[-13, -8, -4], [12, 7, 4], [24, 16, 7]])

In [ ]:
e_vl, e_vec = eig(M)

In [ ]:
e_vl

array([ 3., -1., -1.])

In [ ]:
e_vec                     # each column is an eigencevtor of M

array([[ 0.40824829,  0.57158286,  0.15048813],
       [-0.40824829, -0.55534639,  0.25221658],
       [-0.81649658, -0.6040558 , -0.95589755]])