# Applications of Computational Medicine Issues (Markov Chain)

# Exercise 1: Pandemic Spread Rate-Discrete-Time Case

**Materials and Methods** \\
* To construct the **Discrete-Time Markov Chain Process** model, five states are considered:
  * $S$: Susceptible
  * $Ac$: Active infected
  * $I_n$: Inactive infected
  * $N_a$: Subject dead by natural causes
  * $N_m$: Subject killed by the disease
* The conditional probabilities $p_{ij}$ represent the figures found in a region and are expressed as relative frequencies to transition from state $i$ to state $j$ (see the table below).
* Assume that the incidences, expressed as conditional probabilities, are provided in the table below.

Conditional probabilities for initial-disease (rows) and final-disease (columns).

$$
\begin{array}{l|ccccc}
\hline
         &  S    &  Ac  &  I_n  &  N_a   &  N_m   \\
\hline
 S       & 0.15  & 0.25  & 0.20  & 0.20  & 0.20  \\
 Ac      & 0.10  & 0.35  & 0.45  & 0.05  & 0.05  \\
 I_n      & 0.05  & 0.15  & 0.30  & 0.40  & 0.10  \\
 N_a      & 0.00  & 0.00  & 0.00  & 0.85  & 0.15  \\
 N_m      & 0.00  & 0.00  & 0.00  & 0.15  & 0.85  \\
\hline
\end{array}
$$

* The conditional probabilities in the table above were generated randomly and used to construct the transition matrix $P$ (Eq. (1)).

$$
\begin{equation}
P =
\left( \begin{array}{ccccccccc}
0.15 & 0.25 & 0.20 & 0.20 & 0.20 \\
0.10 & 0.35 & 0.45 & 0.05 & 0.05 \\
0.05 & 0.15 & 0.30 & 0.40 & 0.10 \\
0.00 & 0.00 & 0.00 & 0.85 & 0.15 \\
0.00 & 0.00 & 0.00 & 0.15 & 0.85 \\
  \end{array} \right) \tag{1}
\end{equation}
$$

* The initial state vector: (uniform distribution)

$$
\mathbf{u}_0 = \left( \begin{array}{ccccccc}
1/5 & 1/5 & 1/5 & 1/5 & 1/5 \\
  \end{array} \right)
$$

**Exercise 1** \\
Perform the following tasks:
1. Construt the transition matrix $P$ and verify that the row sum of the transition matrix equals to $1$
2. Compute the first $5$ state vectors
3. (Power method)
 * (a) Compute $P^{50}$ and vertify that the row sum still equals to $1$
 * (b) Compute the state vector after $50$ iterations
 * (c) Repeat tasks (a) and (b) with different initial state vectors $u_0$
 * (d) Verify the row sum of $P^{n}$
 * (e) Compute the steady-state vector
4. Repeat task 3(e) above with nested iteration method

**Task 1.1: Construct the transition matrix** \\
To do: replace `...` below to construct the transition matrix $P$ and verify that the row sum of the transition matrix equals 1 \\
(Hint: the command `np.sum(a, axis=1)` returns the sum of elements of array `a` along the rows and \\
 the command `np.allclose(a, b)` returns `True` if two arrays `a` and `b` are element-wise equal within a tolerance.)

In [16]:
import numpy as np

# Define the transition matrix P
P = np.array([[0.15, 0.25, 0.20, 0.20, 0.20],
              [0.10, 0.35, 0.45, 0.05, 0.05],
              [0.05, 0.15, 0.30, 0.40, 0.10],
              [0.00, 0.00, 0.00, 0.85, 0.15],
              [0.00, 0.00, 0.00, 0.15, 0.85]])

# Check if each row sums to 1
row_sums = np.sum(P, axis=1)
print("Row sums:")
print(np.round(row_sums, 5))

# Optional: Check if all are close to 1
if np.allclose(row_sums, 1.0):
    print("\nAll rows sum to 1 — transition matrix is valid.")
else:
    print("\nWarning: Not all rows sum to 1.")

Row sums:
[1. 1. 1. 1. 1.]

All rows sum to 1 — transition matrix is valid.


**Task 1.2: Compute the first $5$ state vectors** \\
To do: replace `...` below to compute the first $5$ state vectors. (You may test different initial state vectors.) \\
(Hint:
* the command `np.dot(a,b)` returns the dot product or matrix multiplication (depending on the size) of two arrays `a` and `b`
*the command `a.append(elmnt)` appends an element `elmnt` to array `a` )


In [17]:
# Define the initial row vector u0 (uniform distribution)
u0 = np.array([1/5, 1/5, 1/5, 1/5, 1/5])

# Initialize a list to store the state vectors
states = [u0]

# Compute state vectors up to u5
for _ in range(5):
    next_state = np.dot(states[-1], P)
    states.append(next_state)

# Print the results
for i, state in enumerate(states[1:], 1):
    print(f"u{i}:")
    print(state.round(5))  # Rounded for readability
    print()

u1:
[0.06 0.15 0.19 0.33 0.27]

u2:
[0.0335 0.096  0.1365 0.4165 0.3175]

u3:
[0.02145 0.06245 0.09085 0.46775 0.3575 ]

u4:
[0.01401 0.04085 0.05965 0.49496 0.39054]

u5:
[0.00917 0.02674 0.03908 0.508   0.41701]



**Task 1.3(a): (Power method) Compute $P^{50}$** \\
To do: replace `...` below to compute $P^{50}$ and verify that the row sum still equals to $1$ \\
(Hint: the command `np.linalg.matrix_power(a, n)` returns a square matrix `a` to the power n)

In [18]:
# Choose the exponent n
n = 50  # You can change this to any positive integer

# Compute the matrix P^n
P_n = np.linalg.matrix_power(P, n)

# Print the result
print(f"P^{n} =")
print(np.round(P_n, 5))  # Rounded for better readability

# Check if each row sums to 1
row_sums = np.sum(P_n, axis=1)
is_valid = np.allclose(row_sums, 1.0)

# Print result
print(f"Row sums of P^{n}: {np.round(row_sums, 5)}")
print("All rows sum to 1:" , is_valid)

P^50 =
[[0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.5 0.5]
 [0.  0.  0.  0.5 0.5]]
Row sums of P^50: [1. 1. 1. 1. 1.]
All rows sum to 1: True


**Task 1.3(b): Compute the state vector after $50$ iterations** \\
To do: replace `...` below to compute the state vector after $50$ iterations

In [19]:
# Define the initial row vector u0 (uniform distribution)
u0 = np.array([1/5, 1/5, 1/5, 1/5, 1/5]) # You can test different initial state vectors

# Compute u_n = u0 * P^n
u_n = np.dot(u0, P_n)

# Print the final result
print(f"u{n} =")
print(np.round(u_n, 5))

u50 =
[0.  0.  0.  0.5 0.5]


**Task 1.3(c): Repeat tasks (a) and (b) above with different $u_0$** \\
To do: modify the code `u0 = ...` above to test different initial state vector $u_0$

* $\mathbf{u}_0 = \left( \begin{array}{ccccccc}
1/4 & 1/4 & 0 & 1/4 & 1/4 \\
  \end{array} \right)$

* $\mathbf{u}_0 = \left( \begin{array}{ccccccc}
0.11 & 0.11 & 0.26 & 0.26 & 0.26 \\
  \end{array} \right)$

**Task 1.3(d): Verify the row sum of $P^n$** \\
To do: modify the code `n = ...` above to verify the row sum is euqal to $1$ for arbitrary large $n$

**Task 1.3(e): Compute the steady-state vector** \\
To do: modify the code `n = ...` above to  test for the steady-state vector

**Task 1.4: Use nested iteration to compute the steady-state vector** \\
To do: replace `...` below to compute the steady-state vector with nested iteration

In [20]:
# Initial state vector
u = np.array([1/5] * 5)

# Number of iterations
n = 50

# Iteratively multiply to approximate the steady-state vector
for _ in range(n):
    u = np.dot(u, P)

# Print the result
print(f"u{n} =")
print(np.round(u, 5))

u50 =
[0.  0.  0.  0.5 0.5]


# Exercise 2: Pandemic Spread Rate – Continuous-Time Case

**Model Design and Transition Matrix** \\
To design the **Continuous-Time Markov Chain Process** model, a forward transition rate of $0.10$ is considered between states (see the table below), considering that $\lambda_i > \lambda_{i+1}$ and $\mu_i < \mu_{i+1}$.


Matrix of transition probabilities $P$ for a model describing the spread of an event with pandemic potential across three states.

$$
\begin{array}{lccc}
\hline
     &  S  &  I  &  R  \\
\hline
 S  & -\lambda_1   & \lambda_1   & 0 \\
 I  & \mu_1   & -(\mu_1 + \lambda_2) & \lambda_2 \\
 R  & 0 & \mu_2   & -\mu_2 \\
\hline
\end{array}
$$

Let the state vector be:

$$
\begin{equation}
\mathbf{u}  = \left( \begin{array}{ccccccc}
u_1 & u_2 & u_3
  \end{array} \right)  
\end{equation}
$$

Given the transition information:

$$
\left( \begin{array}{ccccccc}
u_1 & u_2 & u_3
  \end{array} \right) \left( \begin{array}{ccccccc}
   -0.10   & 0.10  & 0.00 \\
    0.04   & -( 0.04 + 0.09) & 0.09 \\
    0.00 & 0.06   & -0.06 \\
  \end{array} \right)  = \left( \begin{array}{ccccccc}
0 & 0 & 0
  \end{array} \right)
$$

The system of equations is derived as:

$$
\begin{array}{ccccccc}
-&0.10 u_1 &+& 0.04 u_2 & &          &=& 0 \\
 &0.10 u_1 &-& 0.13 u_2 &+& 0.06 u_3 &=& 0 \\
 &         & & 0.09 u_2 &-& 0.06 u_3 &=& 0
\end{array}
\tag{11}
$$

With the constraint:

$$
u_1 + u_2 + u_3 = 1
\tag{12}
$$

**Exercise 2** \\
Perform the following tasks:
1. Construct the coefficient matrix $A_{eq}$ and constant matrix $b_{eq}$ of the system (Eqs. (11) and (12))
2. Use linear programming method `linprog` to find the steady-state solution $\mathbf{u}$
3. Verify the results in Task 2

**Task 2.1: Construct the coefficient matrix $A_{eq}$ and constant matrix $b_{eq}$** \\
To do: replace `...` below to find $A_{eq}$ and $b_{eq}$

In [21]:
from scipy.optimize import linprog
import numpy as np

# Define the coefficient matrix A_eq based on the system of equations
# Representing:
# -0.10*u1 + 0.04*u2           = 0
#  0.10*u1 - 0.13*u2 + 0.06*u3 = 0
#           0.09*u2 - 0.06*u3 = 0
#  u1 + u2 + u3 = 1

A_eq = np.array([
    [-0.10,  0.04,  0.00],
    [ 0.10, -0.13,  0.06],
    [ 0.00,  0.09, -0.06],
    [ 1.00,  1.00,  1.00]
])

# Right-hand side vector
b_eq = np.array([0, 0, 0, 1])

**Task 2.2: Use linear programming to find $\mathbf{u}$** \\
To do: replace `...` below to find the long-term (steady-state) solution by solving the system using linear programming \\
(Hint: the command `linprog(c, A_eq=A_eq, b_eq=b_eq, method="highs")` solve the following linear programming problem)

$$
\min_x c^Tx \\
\text{such that} \: A_{eq}x = b_{eq}
$$

In [22]:
# Objective function (dummy, since we're solving feasibility only)
c = np.zeros(3)

# Solve the system using linear programming
result = linprog(c, A_eq=A_eq, b_eq=b_eq, method="highs")

# Output results
if result.success:
    u = result.x
    print("Steady-state solution:")
    print(f"u1 = {u[0]:.3f}")
    print(f"u2 = {u[1]:.3f}")
    print(f"u3 = {u[2]:.3f}")

else:
    print("Failed to find solution:", result.message)

Steady-state solution:
u1 = 0.138
u2 = 0.345
u3 = 0.517


**Task 2.3: Verify the results** \\
To do: replace `...` below verify the results in Task 2.2

In [23]:
if result.success:
  # Validate by checking A_eq @ u equals b_eq
      print("Verifying equations (LHS ≈ RHS):")
      lhs = A_eq @ u
      for i, (left, right) in enumerate(zip(lhs, b_eq), 1):
          print(f"Equation {i}: {left:.6f} ≈ {right}")

else:
    print("Failed to find solution:", result.message)

Verifying equations (LHS ≈ RHS):
Equation 1: 0.000000 ≈ 0
Equation 2: -0.000000 ≈ 0
Equation 3: -0.000000 ≈ 0
Equation 4: 1.000000 ≈ 1
