# Applications of Principal Component Analysis



# Exercise 1: Statistical Computations on Vectors

**1.5 Exercise 1** \\
Let

$$
\textbf{x} = \begin{bmatrix}
4 \\
-2 \\
7
\end{bmatrix},
\:\:\:\:\:
\textbf{y} = \begin{bmatrix}
3 \\
4 \\
5
\end{bmatrix}.
$$

Compute the following quantities: \\
(a) The means $\bar{x}$ and $\bar{y}$. \\
(b) The variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$. \\
(c) The covariance $\text{cov}(\textbf{x},\textbf{y})$. \\
(d) The correlation between $\textbf{x}$ and $\textbf{y}$.

**Task 1(a): Compute the means $\bar{x}$ and $\bar{y}$** \\
To do: replace `...` below to input the vectors $\textbf{x}$ and $\textbf{y}$ and then compute the means $\bar{x}$ and $\bar{y}$ \\
(Hint: the command `np.mean(a)` returns the arithmetic mean of array `a`)

In [ ]:
import numpy as np

# Define the input vectors x and y
x = np.array([4, -2, 7])
y = np.array([3, 4, 5])

# (a) Compute sample means
mean_x = np.mean(x)  # Mean of vector x
mean_y = np.mean(y)  # Mean of vector y

# Output the results
print("(a) Sample Means:")
print("Mean of x:", mean_x)
print("Mean of y:", mean_y)

(a) Sample Means:
Mean of x: 3.0
Mean of y: 4.0


**Task 1(b): Compute the variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$** \\
To do: replace `...` below to compute the sample variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$ \\
(Hint: the command `np.var(a, ddof=1)` returns the sample variance of array `a`)

In [ ]:
# (b) Compute sample variances (using ddof=1 for sample variance)
var_x = np.var(x, ddof=1)  # Sample variance of x
var_y = np.var(y, ddof=1)  # Sample variance of y

print("(b) Sample Variances:")
print("Variance of x:", var_x)
print("Variance of y:", var_y)

(b) Sample Variances:
Variance of x: 21.0
Variance of y: 1.0


**Task 1(c): Compute the covariance $\text{cov}(\textbf{x},\textbf{y})$** \\
To do: replace `...` below to compute the sample covariance $\text{cov}(\textbf{x},\textbf{y})$ \\
(Hint: the command `np.cov(a, b)` returns the covariance matrix of arrays `a` and `b`, in which the (0, 1)-entry is the covariance of arrays `a` and `b`)

In [ ]:
# (c) Compute sample covariance
# np.cov returns a covariance matrix; we extract the covariance, which is the [0, 1] element
cov_matrix = np.cov(x, y)
cov_xy = cov_matrix[0, 1]

print("(c) Sample Covariance:")
print("Covariance between x and y:", cov_xy)

(c) Sample Covariance:
Covariance between x and y: 1.5


**Task 1(d): Compute the correlation between $\textbf{x}$ and $\textbf{y}$** \\
To do: replace `...` below to compute the sample correlation between $\textbf{x}$ and $\textbf{y}$ \\
(Hint: the command `np.corrcoef(a, b)` returns the Pearson product-moment correlation coefficients matrix of arrays `a` and `b`, in which the (0, 1)-entry is the sample correlation of arrays `a` and `b`)

In [ ]:
# (d) Compute sample correlation
cor_xy = np.corrcoef(x, y)[0, 1]  # Pearson correlation coefficient

print("(d) Sample Correlation:")
print("Correlation between x and y:", cor_xy)

(d) Sample Correlation:
Correlation between x and y: 0.3273268353539886


# Exercise 2: Performance of Honors Calculus class students

**1.7 Exercise 2** \\
The set of data in the table below was collected by one of the authors from an Honors Calculus class of 14 students. The four variables are:
* ${MT}$: a score from a midterm test (range 1 to 36)
* ${FE}$: final exam score (range 0 to 200)
* ${Qav}$: mean of eight quiz scores (range 0 to 100)
* ${Tav}$: mean of three test scores (range 0 to 100)

**1.7.1 Original Data** \\

$$
\begin{array}{cccccccc}
\hline
Student & MT & FE & Qav & Tav \\
\hline
1 & 33 & 181 & 95 & 89 \\
2 & 31 & 169 & 81 & 89 \\
3 & 21 & 176 & 65 & 68 \\
4 & 25 & 181 & 66 & 90 \\
5 & 29 & 169 & 89 & 81 \\
6 & 24 & 103 & 61 & 57 \\
7 & 24 & 150 & 81 & 76 \\
8 & 29 & 147 & 86 & 76 \\
9 & 36 & 181 & 98 & 102 \\
10 & 26 & 163 & 72 & 70 \\
11 & 31 & 163 & 95 & 81 \\
12 & 29 & 147 & 65 & 67 \\
13 & 23 & 160 & 62 & 68 \\
14 & 26 & 100 & 63 & 56 \\ \hline
\end{array}
$$


Perferm the following tasks: \\
1. * **Original Data**: The data is stored in a NumPy array.
   * **Compute Column Means**: Calculate the mean for each column using `np.mean`.
   *  **Compute Column Standard Deviations**: Calculate the standard deviation for each column using `np.std` with `ddof=1` for sample standard deviation.
2. * **Standardize the Data**: Use the formula
$$
\textbf{z} = \frac{\textbf{x}-\bar{\textbf{x}}}{s_\textbf{x}}
$$
to standardize the data. (obtaining a scaled variable with mean 0 and standard devation 1)
   * **Round the $Z$ Matrix**: Round the standardized values to four decimal places using `np.round`.
3. * **Compute the Correlation Matrix**: Calculate the correlation matrix of the standardized data using `np.corrcoef`.
   * **Round the $C_0$ Matrix**: Round the values to four decimal places using `np.round`.
4. **Perform PCA**: Use PCA from `sklearn.decomposition` to perform principal component analysis.
5. * **Extract the Loadings**: Get the eigenvectors (loadings) from the PCA result using `pca.components_`.
   * **Extract the Eigenvalues**: Get the eigenvalues from the PCA result using `pca.explained_variance_`.
6. **Compute the Proportion of Variance Explained**: Calculate the proportion of variance explained by each principal component.
7. **Compute the Principal Components**: Get the principal components from the PCA result using `pca.transform`.
8. **Print the Results**: Display the correlation matrix, loadings, eigenvalues, proportion of variance explained, and principal components.


**Task 2.1: Compute the means and standard deviations of the variables** \\
To do: replace `...` below to compute the means and standard deviations of the variables $MT, FE, Qav, Tav$ \\
(Hint: the command `np.mean(a, axis=0)` returns the arithmetic mean of array `a` along the columns and \\
the command `np.std(a, axis=0, ddof=1)` returns the sample standard deviation of array `a` along the columns)

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Step 1,1: Original data
data = np.array([
    [33, 181, 95, 89],
    [31, 169, 81, 89],
    [21, 176, 65, 68],
    [25, 181, 66, 90],
    [29, 169, 89, 81],
    [24, 103, 61, 57],
    [24, 150, 81, 76],
    [29, 147, 86, 76],
    [36, 181, 98, 102],
    [26, 163, 72, 70],
    [31, 163, 95, 81],
    [29, 147, 65, 67],
    [23, 160, 62, 68],
    [26, 100, 63, 56]
])

# Step 1.2: Compute column means
mean_values = np.mean(data, axis=0)
print("Column Means:", mean_values)

# Step 1.3: Compute column standard deviations
std_dev_values = np.std(data, axis=0, ddof=1)
print("Column Standard Deviations:", std_dev_values)

Column Means: [ 27.64285714 156.42857143  77.07142857  76.42857143]
Column Standard Deviations: [ 4.21731126 26.11723358 13.74752725 13.19507067]


**Task 2.2: Find the standardized matrix $Z$ of the data** \\
To do: replace `...` below to compute the the standardized matrix $Z$ with scaled variables (standard score)

In [ ]:
# Step 2.1: Standardize the data
Z = (data - mean_values) / std_dev_values

# Step 2.2: Round the Z matrix to four decimal places
Z = np.round(Z, 4)
print("Standardized Data (Z):\n", Z)

Standardized Data (Z):
 [[ 1.2703  0.9408  1.3041  0.9527]
 [ 0.796   0.4813  0.2858  0.9527]
 [-1.5751  0.7494 -0.8781 -0.6388]
 [-0.6267  0.9408 -0.8053  1.0285]
 [ 0.3218  0.4813  0.8677  0.3464]
 [-0.8638 -2.0457 -1.169  -1.4724]
 [-0.8638 -0.2461  0.2858 -0.0325]
 [ 0.3218 -0.361   0.6495 -0.0325]
 [ 1.9816  0.9408  1.5224  1.938 ]
 [-0.3896  0.2516 -0.3689 -0.4872]
 [ 0.796   0.2516  1.3041  0.3464]
 [ 0.3218 -0.361  -0.8781 -0.7146]
 [-1.1009  0.1367 -1.0963 -0.6388]
 [-0.3896 -2.1606 -1.0236 -1.5482]]


**Task 2.3: Find the correlation matrix $C_0$ of the variables** \\
To do: replace `...` below to compute the correlation matrix $C_0$ of the variables \\
(Hint: the command `np.corrcoef(a, rowvar=False)` returns the Pearson product-moment correlation coefficients matrix of `a`, where each column of `a` represents a variable)

In [ ]:
# Step 3: Compute the correlation matrix
C0 = np.corrcoef(Z, rowvar=False)
C0 = np.round(C0, 4)
print("Correlation Matrix (C0):\n", C0)

Correlation Matrix (C0):
 [[1.     0.336  0.8111 0.701 ]
 [0.336  1.     0.4999 0.7958]
 [0.8111 0.4999 1.     0.7487]
 [0.701  0.7958 0.7487 1.    ]]


**Task 2.4: Perform PCA** \\
To do: replace `...` below to perform PCA on $Z$ \\
(Hint: the command `PCA()` initialize a PCA object and  \\
the command `pca.fit(X)` compute the principal components based on the dataset `X`)

In [ ]:
# Step 4: Perform PCA
pca = PCA()
pca.fit(Z)

PCA()

**Task 2.5: Extract the loadings (eigenvectors) and eigenvalues** \\
To do: replace `...` below to find the loadings (eigenvectors) and eigenvalues from PCA result (SVD of $C_0$) \\
(Hint: the command `pca.components_.T` extracts the loadings (eigenvectors) and \\
the command  `pca.explained_variance_` extracts the eigenvalues from the PCA result)


In [ ]:
# Step 5.1: Extract the loadings (eigenvectors)
loadings = pca.components_.T
loadings = np.round(loadings, 4)
print("Loadings (Eigenvectors):\n", loadings)

# Step 5.2: Extract the eigenvalues
eigenvalues = pca.explained_variance_
eigenvalues = np.round(eigenvalues, 4)
print("\nEigenvalues:\n", eigenvalues)

Loadings (Eigenvectors):
 [[ 0.4856 -0.5561 -0.5128 -0.4381]
 [ 0.4378  0.7317  0.064  -0.5185]
 [ 0.5209 -0.3275  0.7848  0.0744]
 [ 0.5489  0.2192 -0.3421  0.7305]]

Eigenvalues:
 [2.9654 0.7592 0.1844 0.091 ]


**Task 2.6: Compute the Proportion of Variance Explained** \\
To do: replace `...` below to calculate the proportion of variance explained (eigenvalues) by each principal component

In [ ]:
# Step 6: Compute the proportion of variance explained
proportion_variance = eigenvalues / np.sum(eigenvalues)
proportion_variance = np.round(proportion_variance, 4)
print("Proportion of Variance Explained:\n", proportion_variance)

Proportion of Variance Explained:
 [0.7413 0.1898 0.0461 0.0228]


**Task 2.7: Find the principal components** \\
To do: replace `...` below to find the principal components from the PCA result \\
(Hint: the command `pca.transform(X)` returns the principal components from the PCA result)

In [ ]:
# Step 11: Compute the principal components
principal_components = pca.transform(Z)
principal_components = np.round(principal_components, 4)
print("Principal Components:\n", principal_components)

Principal Components:
 [[ 2.2309 -0.2363  0.1063 -0.2513]
 [ 1.269   0.0247 -0.479   0.1189]
 [-1.2448  1.5719  0.3851 -0.2305]
 [ 0.2526  1.5261 -0.6022  0.4781]
 [ 1.0091 -0.035   0.4282 -0.0729]
 [-2.732  -0.9564 -0.1017  0.2766]
 [-0.3961  0.1996  0.6626  0.5036]
 [ 0.3187 -0.663   0.3327  0.0708]
 [ 3.2308 -0.4874 -0.4242  0.1731]
 [-0.5386  0.4148  0.093  -0.3431]
 [ 1.3661 -0.6098  0.5128 -0.1291]
 [-0.8514 -0.3122 -0.6328 -0.5412]
 [-1.3964  0.9313 -0.0685 -0.1368]
 [-2.5179 -1.3684 -0.2122  0.0839]]


**Task 2.8: Print the results**

In [ ]:
# Step 8: Print the results
print("Correlation Matrix (C0):")
print(C0)
print("\nLoadings (Eigenvectors)")
print(loadings)
print("\nEigenvalues:")
print(eigenvalues)
print("\nProportion of Variance Explained:")
print(proportion_variance)
print("\nPrincipal Components:")
print(principal_components)

Correlation Matrix (C0):
[[1.     0.336  0.8111 0.701 ]
 [0.336  1.     0.4999 0.7958]
 [0.8111 0.4999 1.     0.7487]
 [0.701  0.7958 0.7487 1.    ]]

Loadings (Eigenvectors)
[[ 0.4856 -0.5561 -0.5128 -0.4381]
 [ 0.4378  0.7317  0.064  -0.5185]
 [ 0.5209 -0.3275  0.7848  0.0744]
 [ 0.5489  0.2192 -0.3421  0.7305]]

Eigenvalues:
[2.9654 0.7592 0.1844 0.091 ]

Proportion of Variance Explained:
[0.7413 0.1898 0.0461 0.0228]

Principal Components:
[[ 2.2309 -0.2363  0.1063 -0.2513]
 [ 1.269   0.0247 -0.479   0.1189]
 [-1.2448  1.5719  0.3851 -0.2305]
 [ 0.2526  1.5261 -0.6022  0.4781]
 [ 1.0091 -0.035   0.4282 -0.0729]
 [-2.732  -0.9564 -0.1017  0.2766]
 [-0.3961  0.1996  0.6626  0.5036]
 [ 0.3187 -0.663   0.3327  0.0708]
 [ 3.2308 -0.4874 -0.4242  0.1731]
 [-0.5386  0.4148  0.093  -0.3431]
 [ 1.3661 -0.6098  0.5128 -0.1291]
 [-0.8514 -0.3122 -0.6328 -0.5412]
 [-1.3964  0.9313 -0.0685 -0.1368]
 [-2.5179 -1.3684 -0.2122  0.0839]]


# Exercise 3: Tests scores in Algebra, Trigonometry, English Literature and Chinese Literature

**1.8 Exercise 3** \\
Principal Component Analysis: Test Scores in Mathematics, English Literature , and Chinese Literature

A group of ten students took four tests: two in mathematics (Algebra (abbreviated as $Alg$) and Trigonometry (abbreviated as $Trig$)), one in English Literature (abbreviated as $Englit$), and one in Chinese Literature (abbreviated as $Chilit$). The following table presents both the original and the scaled scores.

**1.8.1 Original and Scaled Test Scores** \\

$$
\begin{array}{cccccccc}
\hline
Student & Alg & Trig & Englit & Chilit \\
\hline
1  & 95 & 88 & 65 & 68 \\
2  & 87 & 92 & 70 & 74 \\
3  & 75 & 78 & 75 & 72 \\
4  & 74 & 70 & 85 & 81 \\
5  & 46 & 51 & 92 & 95 \\
6  & 62 & 55 & 88 & 90 \\
7  & 82 & 91 & 85 & 90 \\
8  & 68 & 52 & 55 & 60 \\
9  & 82 & 78 & 80 & 75 \\
10 & 65 & 70 & 72 & 70 \\
\hline
\end{array}
$$

Perferm the following tasks: (refer to Exercise 2) \\
1. * **Original Data**: The data is stored in a NumPy array.
   * **Compute Column Means**: Calculate the mean for each column using `np.mean`.
   *  **Compute Column Standard Deviations**: Calculate the standard deviation for each column using `np.std` with `ddof=1` for sample standard deviation.
2. * **Standardize the Data**: Use the formula
$$
\textbf{z} = \frac{\textbf{x}-\bar{\textbf{x}}}{s_\textbf{x}}
$$
to standardize the data. (obtaining a scaled variable with mean 0 and standard devation 1)
   * **Round the $Z$ Matrix**: Round the standardized values to four decimal places using `np.round`.
3. * **Compute the Correlation Matrix**: Calculate the correlation matrix of the standardized data using `np.corrcoef`.
   * **Round the $C_0$ Matrix**: Round the values to four decimal places using `np.round`.
4. **Perform PCA**: Use PCA from `sklearn.decomposition` to perform principal component analysis.
5. * **Extract the Loadings**: Get the eigenvectors (loadings) from the PCA result using `pca.components_`.
   * **Extract the Eigenvalues**: Get the eigenvalues from the PCA result using `pca.explained_variance_`.
6. **Compute the Proportion of Variance Explained**: Calculate the proportion of variance explained by each principal component.
7. **Compute the Principal Components**: Get the principal components from the PCA result using `pca.transform`.
8. **Print the Results**: Display the correlation matrix, loadings, eigenvalues, proportion of variance explained, and principal components.


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Step 1,1: Original data
data = np.array([
    [95, 88, 65, 68],
    [87, 92, 70, 74],
    [75, 78, 75, 72],
    [74, 70, 85, 81],
    [46, 51, 92, 95],
    [62, 55, 88, 90],
    [82, 91, 85, 90],
    [68, 52, 55, 60],
    [82, 78, 80, 75],
    [65, 70, 72, 70]
])

# Step 1.2: Compute column means
mean_values = np.mean(data, axis=0)
print("Column Means:", mean_values)

# Step 1.3: Compute column standard deviations
std_dev_values = np.std(data, axis=0, ddof=1)
print("Column Standard Deviations:", std_dev_values)

Column Means: [73.6 72.5 76.7 77.5]
Column Standard Deviations: [14.07282646 15.72153512 11.48960883 11.21754578]


In [ ]:
# Step 2.1: Standardize the data
Z = (data - mean_values) / std_dev_values

# Step 2.2: Round the Z matrix to four decimal places
Z = np.round(Z, 4)
print("Standardized Data (Z):\n", Z)

Standardized Data (Z):
 [[ 1.5207  0.9859 -1.0183 -0.8469]
 [ 0.9522  1.2403 -0.5831 -0.312 ]
 [ 0.0995  0.3498 -0.148  -0.4903]
 [ 0.0284 -0.159   0.7224  0.312 ]
 [-1.9612 -1.3676  1.3316  1.5601]
 [-0.8243 -1.1131  0.9835  1.1143]
 [ 0.5969  1.1767  0.7224  1.1143]
 [-0.3979 -1.3039 -1.8887 -1.5601]
 [ 0.5969  0.3498  0.2872 -0.2229]
 [-0.6111 -0.159  -0.4091 -0.6686]]


In [ ]:
# Step 3: Compute the correlation matrix
C0 = np.corrcoef(Z, rowvar=False)
C0 = np.round(C0, 4)
print("Correlation Matrix (C0):\n", C0)

Correlation Matrix (C0):
 [[ 1.      0.8708 -0.4351 -0.4491]
 [ 0.8708  1.     -0.1479 -0.1604]
 [-0.4351 -0.1479  1.      0.9418]
 [-0.4491 -0.1604  0.9418  1.    ]]


In [ ]:
# Step 4: Perform PCA
pca = PCA()
pca.fit(Z)

PCA()

In [ ]:
# Step 5.1: Extract the loadings (eigenvectors)
loadings = pca.components_.T
loadings = np.round(loadings, 4)
print("Loadings (Eigenvectors):\n", loadings)

# Step 5.2: Extract the eigenvalues
eigenvalues = pca.explained_variance_
eigenvalues = np.round(eigenvalues, 4)
print("\nEigenvalues:\n", eigenvalues)

Loadings (Eigenvectors):
 [[ 0.5381  0.4114  0.7335  0.0564]
 [ 0.413   0.6321 -0.6544 -0.0396]
 [-0.517   0.4696  0.1694 -0.6954]
 [-0.5221  0.459   0.0706  0.7154]]

Eigenvalues:
 [2.5223 1.3403 0.0794 0.058 ]


In [ ]:
# Step 6: Compute the proportion of variance explained
proportion_variance = eigenvalues / np.sum(eigenvalues)
proportion_variance = np.round(proportion_variance, 4)
print("Proportion of Variance Explained:\n", proportion_variance)

Proportion of Variance Explained:
 [0.6306 0.3351 0.0198 0.0145]


In [ ]:
# Step 11: Compute the principal components
principal_components = pca.transform(Z)
principal_components = np.round(principal_components, 4)
print("Principal Components:\n", principal_components)

Principal Components:
 [[ 2.1941  0.3818  0.2381  0.149 ]
 [ 1.489   0.7587 -0.234   0.1869]
 [ 0.5305 -0.0325 -0.2156 -0.2561]
 [-0.5868  0.3936  0.2692 -0.2712]
 [-3.1231 -0.3298 -0.208   0.1336]
 [-1.9935 -0.0693  0.369   0.1108]
 [-0.1481  1.8401 -0.1313  0.2819]
 [ 1.0383 -2.5909  0.1315  0.2265]
 [ 0.4336  0.4992  0.2418 -0.3393]
 [ 0.1661 -0.8509 -0.4607 -0.222 ]]


In [ ]:
# Step 8: Print the results
print("Correlation Matrix (C0):")
print(C0)
print("\nLoadings (Eigenvectors)")
print(loadings)
print("\nEigenvalues:")
print(eigenvalues)
print("\nProportion of Variance Explained:")
print(proportion_variance)
print("\nPrincipal Components:")
print(principal_components)

Correlation Matrix (C0):
[[ 1.      0.8708 -0.4351 -0.4491]
 [ 0.8708  1.     -0.1479 -0.1604]
 [-0.4351 -0.1479  1.      0.9418]
 [-0.4491 -0.1604  0.9418  1.    ]]

Loadings (Eigenvectors)
[[ 0.5381  0.4114  0.7335  0.0564]
 [ 0.413   0.6321 -0.6544 -0.0396]
 [-0.517   0.4696  0.1694 -0.6954]
 [-0.5221  0.459   0.0706  0.7154]]

Eigenvalues:
[2.5223 1.3403 0.0794 0.058 ]

Proportion of Variance Explained:
[0.6306 0.3351 0.0198 0.0145]

Principal Components:
[[ 2.1941  0.3818  0.2381  0.149 ]
 [ 1.489   0.7587 -0.234   0.1869]
 [ 0.5305 -0.0325 -0.2156 -0.2561]
 [-0.5868  0.3936  0.2692 -0.2712]
 [-3.1231 -0.3298 -0.208   0.1336]
 [-1.9935 -0.0693  0.369   0.1108]
 [-0.1481  1.8401 -0.1313  0.2819]
 [ 1.0383 -2.5909  0.1315  0.2265]
 [ 0.4336  0.4992  0.2418 -0.3393]
 [ 0.1661 -0.8509 -0.4607 -0.222 ]]
